import { useState } from 'react';

interface MFAStepProps {
  onSubmit: (code: string) => void;
  onBack: () => void;
}

function MFAStep({ onSubmit, onBack }: MFAStepProps) {
  const [code, setCode] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length >= 6) {
      onSubmit(code);
    }
  };

  return (
    <div className="login-step">
      <h2>Enter Passcode</h2>
      <p>Enter the passcode generated by your authenticator app</p>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <input
            type="text"
            id="mfa"
            value={code}
            onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
            maxLength={6}
            required
          />
        </div>
        <div className="button-group">
          <button type="submit" className="btn-primary">
            Submit
          </button>
          <button type="button" onClick={onBack} className="btn-secondary">
            Cancel
          </button>
        </div>
        <div className="login-links">
          <a href="#">Verify another way</a> | <a href="#">Help</a>
        </div>
      </form>
    </div>
  );
}

export default MFAStep;

